# Generated by Django 4.2.2 on 2023-06-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='cdl')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drvb.referral')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
