# Generated by Django 4.2.2 on 2023-06-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drvb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='dln',
            field=models.CharField(default=True, max_length=200, unique=True),
        ),
    ]
