# Generated by Django 4.2.2 on 2023-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drvb', '0002_driver_dln'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='dln',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
